services:
  solid-server:
    image: solidproject/community-server:3.0
    volumes:
      - ./config/solid/:/config/
    ports:
      - 3000:3000
    command: -c /config/sparql.json -s http://triplestore:8890/sparql
  triplestore:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.application.com/my-graph"
    volumes:
      - ./data/virtuoso:/data