services:
  solid-server:
    image: redpencil/mashlib-solid-server:0.0.3
    environment:
      SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
    ports:
      - 3000:3000

  triplestore:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.application.com/my-graph"
    volumes:
      - ./data/virtuoso:/data