x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  solid-server:
    image: redpencil/mashlib-solid-server:0.1.0-beta.1
    volumes:
      - ./config/solid/:/config/

      - ./templates/:/templates/
    environment:
      SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      CONFIG_FILE: "/config/file_based/mashlib-files.json"
      ROOT_FILE_PATH: "./data"

  triplestore:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/virtuoso:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    logging: *default-logging
