services:
  triplestore:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.application.com/my-graph"
    volumes:
      - ./data/virtuoso:/data
    ports:
      - 8890:8890