x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  solid-server:
    image: redpencil/mashlib-solid-server:feature-design-tryouts
    volumes:
      - ./data/pods:/usr/app/data
