services:
  solid:
    expose:
      - 3000
    networks:
      - proxy
      - default
    environment:
      BASE_URL: "https://solid.redpencil.io"
      VIRTUAL_HOST: "solid.redpencil.io"
      LETSENCRYPT_HOST: "solid.redpencil.io"
      LETSENCRYPT_EMAIL: "support@redpencil.io"
    restart: always
  triplestore:
    restart: always
networks:
  proxy:
    external:
      name: letsencrypt_default
